ALTER TABLE blind_date_character MODIFY char_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE date_course MODIFY course_id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE chatroom MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

CREATE TABLE ranking (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    usn BIGINT NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    profile_img VARCHAR(255) NOT NULL,
    score INT UNSIGNED NOT NULL,
    achieved_time TIMESTAMP NOT NULL
);
